title:  Noah Moroze 
tagline: 
author:
  name: 'Noah Moroze'
  twitter: noahmoroze 

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: UA-82132124-2

menu:
- {name: 'Blog', url: 'blog'}
- {name: 'Projects', url: 'projects'}

social:
- {icon: 'github', link: 'https://www.github.com/nmoroze'}
- {icon: 'medium', link: 'https://medium.com/@noahmoroze'}
- {icon: 'twitter', link: 'https://twitter.com/noahmoroze'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/noah-moroze-715173a0'}
- {icon: 'envelope', link: 'mailto:me@noahmoroze.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
